version: 2.1
orbs:
  go: gotest/tools@0.0.9
  codecov: codecov/codecov@1.0.2

executors:
  golang:
    docker:
      - image: circleci/golang:1.13

commands:
  install-deps:
    steps:
      - go/install-ssh
      - go/install: {package: git}
  prepare:
    parameters:
      linux:
        default: true
        description: is a linux build environment?
        type: boolean
    steps:
      - checkout
      - when:
          condition: << parameters.linux >>
          steps:
            - run: sudo apt-get update
  build-all:


jobs:
  mod-tidy-check:
    executor: golang
    steps:
      - install-deps
      - prepare
      - go/mod-download
      - go/mod-tidy-check

  build-all:
    executor: golang
    steps:
      - install-deps
      - prepare
      - go/mod-download
      - run:
          command: make build
      - store_artifacts:
          path: specs-actors
      - store_artifacts:
          path: specs-actors

  check-gen:
    executor: golang
    steps:
      - install-deps
      - prepare
      - go/mod-download
      - run:
          name: "Install goimports"
          command: |
            cd / && go get golang.org/x/tools/cmd/goimports
      - run:
          name: "Ensure we don't need to run 'make gen'"
          command: |
            make gen && git diff --exit-code

  test-all:
    executor: golang
    steps:
      - install-deps
      - prepare
      - go/mod-download
      - run:
          command: |
            make test-coverage
            mkdir -p /tmp/artifacts
            mv coverage.out /tmp/artifacts/coverage.out
            make test-migration
      - codecov/upload:
          file: /tmp/artifacts/coverage.out
      - store_artifacts:
          path: specs-actors

  lint: &lint
    description: |
      Run golangci-lint.
    parameters:
      executor:
        type: executor
        default: golang
      golangci-lint-version:
        type: string
        default: 1.28.2
      concurrency:
        type: string
        default: '2'
        description: |
          Concurrency used to run linters. Defaults to 2 because NumCPU is not
          aware of container CPU limits.
      args:
        type: string
        default: ''
        description: |
          Arguments to pass to golangci-lint
    executor: << parameters.executor >>
    steps:
      - install-deps
      - prepare
      - run:
          command: make -j3 support/tools/bin/golangci-lint support/tools/bin/no-map-range.so
      - run:
          name: Lint
          command: |
            support/tools/bin/golangci-lint run -v \
              --concurrency << parameters.concurrency >> << parameters.args >>

  lint-all:
    <<: *lint

workflows:
  version: 2.1
  ci:
    jobs:
      - lint-all
      - mod-tidy-check
      - build-all
      - test-all
      - check-gen
